# Generated by Django 3.2 on 2023-01-31 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'آدرس', 'verbose_name_plural': 'آدرس ها'},
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='email',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='last_name',
            field=models.CharField(default=1, max_length=50, verbose_name='نام خانوادگی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermodel',
            name='name',
            field=models.CharField(default=2, max_length=50, verbose_name='نام'),
            preserve_default=False,
        ),
    ]
