# Generated by Django 3.2 on 2023-01-31 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_usermodel_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermodel',
            options={'verbose_name': 'مشتری', 'verbose_name_plural': 'مشتری ها'},
        ),
    ]
