# Generated by Django 3.2 on 2023-02-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodmodel',
            options={'verbose_name': 'غذا', 'verbose_name_plural': ' غذا ها'},
        ),
        migrations.AddField(
            model_name='foodmodel',
            name='available',
            field=models.BooleanField(default=True, verbose_name='وضعیت'),
        ),
    ]
