# Generated by Django 3.2 on 2023-02-04 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitems',
            old_name='product',
            new_name='food',
        ),
    ]
