# Generated by Django 3.2 on 2023-02-12 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_orders_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='description',
            field=models.TextField(blank=True, max_length=600, null=True, verbose_name='درباره سفارش'),
        ),
    ]
