# Generated by Django 3.2 on 2023-02-13 21:55

from django.db import migrations, models
from django.utils import timezone

class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_orders_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now(), verbose_name='زمان ثبت سفارش'),
            preserve_default=False,
        ),
    ]
