# Generated by Django 3.2 on 2023-02-13 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_alter_orders_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='date',
        ),
    ]
