# Generated by Django 3.2 on 2023-02-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_orders_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='undo',
            field=models.BooleanField(default=False, verbose_name='وضعیت فیش'),
        ),
    ]
